services:
  api:
    build:
      context: .
      dockerfile: build/Dockerfile.api
    environment:
      - TELEGRAM_BASE_URL_WITH_TOKEN=${TELEGRAM_BASE_URL_WITH_TOKEN}
    volumes:
      - ./.env:/app/.env:ro
    ports:
      - "8080:50052"
    networks:
      - moodnet
    depends_on:
      - kafka
    deploy:
      resources:
        limits:
          memory: 256M
    mem_limit: 256m

  notification:
    build:
      context: .
      dockerfile: build/Dockerfile.notification
    networks:
      - moodnet
    deploy:
      resources:
        limits:
          memory: 256M
    mem_limit: 256m

  storage:
    build:
      context: .
      dockerfile: build/Dockerfile.storage
    ports:
      - "8081:50051"
    networks:
      - moodnet
    depends_on:
      - kafka
    deploy:
      resources:
        limits:
          memory: 256M
    mem_limit: 256m

  zookeeper:
      image: confluentinc/cp-zookeeper:7.5.0
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
      networks:
        - moodnet

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - moodnet

networks:
  moodnet:
    driver: bridge
