// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pb/apipb/api.proto

package apipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pb_apipb_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pb_apipb_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pb_apipb_api_proto_rawDescGZIP(), []int{0}
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_pb_apipb_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_pb_apipb_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_pb_apipb_api_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_pb_apipb_api_proto protoreflect.FileDescriptor

const file_pb_apipb_api_proto_rawDesc = "" +
	"\n" +
	"\x12pb/apipb/api.proto\x12\x05apipb\"\a\n" +
	"\x05Empty\"\"\n" +
	"\bResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2u\n" +
	"\n" +
	"ApiService\x126\n" +
	"\x15SendEmotionCategories\x12\f.apipb.Empty\x1a\x0f.apipb.Response\x12/\n" +
	"\x0eSendStatistics\x12\f.apipb.Empty\x1a\x0f.apipb.ResponseB\n" +
	"Z\bpb/apipbb\x06proto3"

var (
	file_pb_apipb_api_proto_rawDescOnce sync.Once
	file_pb_apipb_api_proto_rawDescData []byte
)

func file_pb_apipb_api_proto_rawDescGZIP() []byte {
	file_pb_apipb_api_proto_rawDescOnce.Do(func() {
		file_pb_apipb_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_apipb_api_proto_rawDesc), len(file_pb_apipb_api_proto_rawDesc)))
	})
	return file_pb_apipb_api_proto_rawDescData
}

var file_pb_apipb_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_apipb_api_proto_goTypes = []any{
	(*Empty)(nil),    // 0: apipb.Empty
	(*Response)(nil), // 1: apipb.Response
}
var file_pb_apipb_api_proto_depIdxs = []int32{
	0, // 0: apipb.ApiService.SendEmotionCategories:input_type -> apipb.Empty
	0, // 1: apipb.ApiService.SendStatistics:input_type -> apipb.Empty
	1, // 2: apipb.ApiService.SendEmotionCategories:output_type -> apipb.Response
	1, // 3: apipb.ApiService.SendStatistics:output_type -> apipb.Response
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_apipb_api_proto_init() }
func file_pb_apipb_api_proto_init() {
	if File_pb_apipb_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_apipb_api_proto_rawDesc), len(file_pb_apipb_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_apipb_api_proto_goTypes,
		DependencyIndexes: file_pb_apipb_api_proto_depIdxs,
		MessageInfos:      file_pb_apipb_api_proto_msgTypes,
	}.Build()
	File_pb_apipb_api_proto = out.File
	file_pb_apipb_api_proto_goTypes = nil
	file_pb_apipb_api_proto_depIdxs = nil
}
