// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pb/storagepb/storage.proto

package storagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pb_storagepb_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storagepb_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pb_storagepb_storage_proto_rawDescGZIP(), []int{0}
}

type SendChatIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ChatIDs       []int64                `protobuf:"varint,2,rep,packed,name=chatIDs,proto3" json:"chatIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendChatIDsResponse) Reset() {
	*x = SendChatIDsResponse{}
	mi := &file_pb_storagepb_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendChatIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChatIDsResponse) ProtoMessage() {}

func (x *SendChatIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storagepb_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChatIDsResponse.ProtoReflect.Descriptor instead.
func (*SendChatIDsResponse) Descriptor() ([]byte, []int) {
	return file_pb_storagepb_storage_proto_rawDescGZIP(), []int{1}
}

func (x *SendChatIDsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SendChatIDsResponse) GetChatIDs() []int64 {
	if x != nil {
		return x.ChatIDs
	}
	return nil
}

type GetStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chatId,proto3" json:"chatId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatisticsRequest) Reset() {
	*x = GetStatisticsRequest{}
	mi := &file_pb_storagepb_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsRequest) ProtoMessage() {}

func (x *GetStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storagepb_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_pb_storagepb_storage_proto_rawDescGZIP(), []int{2}
}

func (x *GetStatisticsRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type Emotion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Emotion) Reset() {
	*x = Emotion{}
	mi := &file_pb_storagepb_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Emotion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Emotion) ProtoMessage() {}

func (x *Emotion) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storagepb_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Emotion.ProtoReflect.Descriptor instead.
func (*Emotion) Descriptor() ([]byte, []int) {
	return file_pb_storagepb_storage_proto_rawDescGZIP(), []int{3}
}

func (x *Emotion) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Emotion) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Emotions      []*Emotion             `protobuf:"bytes,2,rep,name=emotions,proto3" json:"emotions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_pb_storagepb_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storagepb_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_pb_storagepb_storage_proto_rawDescGZIP(), []int{4}
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetEmotions() []*Emotion {
	if x != nil {
		return x.Emotions
	}
	return nil
}

type StatisticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatisticsResponse) Reset() {
	*x = StatisticsResponse{}
	mi := &file_pb_storagepb_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsResponse) ProtoMessage() {}

func (x *StatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storagepb_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsResponse.ProtoReflect.Descriptor instead.
func (*StatisticsResponse) Descriptor() ([]byte, []int) {
	return file_pb_storagepb_storage_proto_rawDescGZIP(), []int{5}
}

func (x *StatisticsResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

var File_pb_storagepb_storage_proto protoreflect.FileDescriptor

const file_pb_storagepb_storage_proto_rawDesc = "" +
	"\n" +
	"\x1apb/storagepb/storage.proto\x12\tstoragepb\"\a\n" +
	"\x05Empty\"G\n" +
	"\x13SendChatIDsResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\achatIDs\x18\x02 \x03(\x03R\achatIDs\".\n" +
	"\x14GetStatisticsRequest\x12\x16\n" +
	"\x06chatId\x18\x01 \x01(\x03R\x06chatId\"3\n" +
	"\aEmotion\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"N\n" +
	"\bCategory\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12.\n" +
	"\bemotions\x18\x02 \x03(\v2\x12.storagepb.EmotionR\bemotions\"I\n" +
	"\x12StatisticsResponse\x123\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x13.storagepb.CategoryR\n" +
	"categories2\xa1\x01\n" +
	"\x0eStorageService\x12>\n" +
	"\n" +
	"GetChatIDs\x12\x10.storagepb.Empty\x1a\x1e.storagepb.SendChatIDsResponse\x12O\n" +
	"\rGetStatistics\x12\x1f.storagepb.GetStatisticsRequest\x1a\x1d.storagepb.StatisticsResponseB\x0eZ\fpb/storagepbb\x06proto3"

var (
	file_pb_storagepb_storage_proto_rawDescOnce sync.Once
	file_pb_storagepb_storage_proto_rawDescData []byte
)

func file_pb_storagepb_storage_proto_rawDescGZIP() []byte {
	file_pb_storagepb_storage_proto_rawDescOnce.Do(func() {
		file_pb_storagepb_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_storagepb_storage_proto_rawDesc), len(file_pb_storagepb_storage_proto_rawDesc)))
	})
	return file_pb_storagepb_storage_proto_rawDescData
}

var file_pb_storagepb_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pb_storagepb_storage_proto_goTypes = []any{
	(*Empty)(nil),                // 0: storagepb.Empty
	(*SendChatIDsResponse)(nil),  // 1: storagepb.SendChatIDsResponse
	(*GetStatisticsRequest)(nil), // 2: storagepb.GetStatisticsRequest
	(*Emotion)(nil),              // 3: storagepb.Emotion
	(*Category)(nil),             // 4: storagepb.Category
	(*StatisticsResponse)(nil),   // 5: storagepb.StatisticsResponse
}
var file_pb_storagepb_storage_proto_depIdxs = []int32{
	3, // 0: storagepb.Category.emotions:type_name -> storagepb.Emotion
	4, // 1: storagepb.StatisticsResponse.categories:type_name -> storagepb.Category
	0, // 2: storagepb.StorageService.GetChatIDs:input_type -> storagepb.Empty
	2, // 3: storagepb.StorageService.GetStatistics:input_type -> storagepb.GetStatisticsRequest
	1, // 4: storagepb.StorageService.GetChatIDs:output_type -> storagepb.SendChatIDsResponse
	5, // 5: storagepb.StorageService.GetStatistics:output_type -> storagepb.StatisticsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_storagepb_storage_proto_init() }
func file_pb_storagepb_storage_proto_init() {
	if File_pb_storagepb_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_storagepb_storage_proto_rawDesc), len(file_pb_storagepb_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_storagepb_storage_proto_goTypes,
		DependencyIndexes: file_pb_storagepb_storage_proto_depIdxs,
		MessageInfos:      file_pb_storagepb_storage_proto_msgTypes,
	}.Build()
	File_pb_storagepb_storage_proto = out.File
	file_pb_storagepb_storage_proto_goTypes = nil
	file_pb_storagepb_storage_proto_depIdxs = nil
}
