// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pb/storage/storage.proto

package storagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddMoodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Mood          string                 `protobuf:"bytes,2,opt,name=mood,proto3" json:"mood,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMoodRequest) Reset() {
	*x = AddMoodRequest{}
	mi := &file_pb_storage_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMoodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMoodRequest) ProtoMessage() {}

func (x *AddMoodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storage_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMoodRequest.ProtoReflect.Descriptor instead.
func (*AddMoodRequest) Descriptor() ([]byte, []int) {
	return file_pb_storage_storage_proto_rawDescGZIP(), []int{0}
}

func (x *AddMoodRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *AddMoodRequest) GetMood() string {
	if x != nil {
		return x.Mood
	}
	return ""
}

type AddMoodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMoodResponse) Reset() {
	*x = AddMoodResponse{}
	mi := &file_pb_storage_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMoodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMoodResponse) ProtoMessage() {}

func (x *AddMoodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storage_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMoodResponse.ProtoReflect.Descriptor instead.
func (*AddMoodResponse) Descriptor() ([]byte, []int) {
	return file_pb_storage_storage_proto_rawDescGZIP(), []int{1}
}

func (x *AddMoodResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_pb_storage_storage_proto protoreflect.FileDescriptor

const file_pb_storage_storage_proto_rawDesc = "" +
	"\n" +
	"\x18pb/storage/storage.proto\x12\tstoragepb\"=\n" +
	"\x0eAddMoodRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x12\n" +
	"\x04mood\x18\x02 \x01(\tR\x04mood\")\n" +
	"\x0fAddMoodResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2R\n" +
	"\x0eStorageService\x12@\n" +
	"\aAddMood\x12\x19.storagepb.AddMoodRequest\x1a\x1a.storagepb.AddMoodResponseB\x0eZ\fpb/storagepbb\x06proto3"

var (
	file_pb_storage_storage_proto_rawDescOnce sync.Once
	file_pb_storage_storage_proto_rawDescData []byte
)

func file_pb_storage_storage_proto_rawDescGZIP() []byte {
	file_pb_storage_storage_proto_rawDescOnce.Do(func() {
		file_pb_storage_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_storage_storage_proto_rawDesc), len(file_pb_storage_storage_proto_rawDesc)))
	})
	return file_pb_storage_storage_proto_rawDescData
}

var file_pb_storage_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_storage_storage_proto_goTypes = []any{
	(*AddMoodRequest)(nil),  // 0: storagepb.AddMoodRequest
	(*AddMoodResponse)(nil), // 1: storagepb.AddMoodResponse
}
var file_pb_storage_storage_proto_depIdxs = []int32{
	0, // 0: storagepb.StorageService.AddMood:input_type -> storagepb.AddMoodRequest
	1, // 1: storagepb.StorageService.AddMood:output_type -> storagepb.AddMoodResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_storage_storage_proto_init() }
func file_pb_storage_storage_proto_init() {
	if File_pb_storage_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_storage_storage_proto_rawDesc), len(file_pb_storage_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_storage_storage_proto_goTypes,
		DependencyIndexes: file_pb_storage_storage_proto_depIdxs,
		MessageInfos:      file_pb_storage_storage_proto_msgTypes,
	}.Build()
	File_pb_storage_storage_proto = out.File
	file_pb_storage_storage_proto_goTypes = nil
	file_pb_storage_storage_proto_depIdxs = nil
}
